version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge
