version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/policy_crew
    ports:
      - "8000:8000"
    networks:
      - policy_network

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/policy_crew
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - policy_network

networks:
  policy_network:
    driver: bridge
