name: Run Giskard Evals on Hyperparameter Changes

on:
  pull_request:
    paths:
      - 'hyper-parameters.yaml'

jobs:
  run-evals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt

    - name: Run Evals
      run: |
        python evals/giskard_evals.py
      env:
        QDRANT_URL: ${{ secrets.QDRANT_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}

    - name: Upload Giskard report
      uses: actions/upload-artifact@v2
      id: upload-giskard-report
      with:
        name: giskard-report
        path: ./evals/giskard-report.html

    - name: Get Artifact URL
      id: get-artifact-url
      run: echo "::set-output name=url::https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ steps.upload-giskard-report.outputs.artifact_id }}"

    - name: Add report as comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Here is the [Giskard report](${{ steps.get-artifact-url.outputs.url }}) generated for this pull request.
