name: Run Giskard Evals on Hyperparameter Changes

on:
  pull_request:
    paths:
      - 'hyper-parameters.yaml'

jobs:
  run-evals:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt
        pip install requests

    - name: Run Evals
      run: |
        python evals/giskard_evals.py
      env:
        QDRANT_URL: ${{ secrets.QDRANT_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

