name: Run Giskard Evals on Hyperparameter Changes

on:
  pull_request:
    paths:
      - 'hyper-parameters.yaml'

jobs:
  run-evals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt

    - name: Run Evals
      run: |
        python evals/giskard_evals.py
      env:
        qdrant_url: ${{ secrets.OPENAI_URL }}
        qdrant_api_key: ${{ secrets.QDRANT_API_KEY }}
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        jina_api_key: ${{ secrets.JINA_API_KEY }}

    - name: Upload Giskard report
      uses: actions/upload-artifact@v2
      with:
        name: giskard-report
        path: ./evals/giskard-report.html

    - name: Add report as comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Here is the [Giskard report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/giskard-report) generated for this pull request.
