name: Run Giskard Evals on Hyperparameter Changes

on:
  pull_request:
    paths:
      - 'hyper-parameters.yaml'

jobs:
  run-evals:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt

    - name: Run Evals
      run: |
        python evals/giskard_evals.py
      env:
        QDRANT_URL: ${{ secrets.OPENAI_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        
    - name: Upload Giskard report
      uses: actions/upload-artifact@v2
      with:
        name: giskard-report
        path: evals/giskard-report.html

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: evals
        destination_dir: reports/${{ github.event.pull_request.number }}
        enable_jekyll: false

    - name: Add report as comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const reportUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/reports/${context.issue.number}/giskard-report.html`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `The Giskard report for this pull request is available [here](${reportUrl}). This report includes all necessary styling.`
          });
