name: Run Giskard Evals on Hyperparameter Changes

on:
  pull_request:
    paths:
      - 'hyper-parameters.yaml'

jobs:
  run-evals:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt

    - name: Run Evals
      run: |
        python evals/giskard_evals.py
      env:
        QDRANT_URL: ${{ secrets.QDRANT_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

    - name: Add report as comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Here are the test suite results for this pull request:
          ${{ steps.run-evals.outputs.test_suite_results }}
